### ISSUE TITLE
Segmentation Fault on Kubuntu

### ISSUE THREAD

**Issue by greengameplayer** [OperatorFoundation/shapeshifter-dispatcher#23]
```bash
sudo ~/go/bin/shapeshifter-dispatcher -transparent -client -state state -target (removed):2222 -transports obfs4 -proxylistenaddr 127.0.0.1:1443 -options '{"cert": "(removed)", "iat-mode": "0"}' 
-logLevel DEBUG -enableLogging
```
```
[sudo] password for (removed): 
checking for optionsFile
```
```
Dialing  (removed):2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x48fe91]

goroutine 5 [running]:
io.copyBuffer(0x826020, 0xc000022020, 0x0, 0x0, 0xc00014c000, 0x8000, 0x8000, 0xc000038678, 0x40a1b6, 0xaa44f8)
        /usr/lib/go-1.12/src/io/io.go:402 +0x101
io.Copy(...)
        /usr/lib/go-1.12/src/io/io.go:364
net.genericReadFrom(...)
        /usr/lib/go-1.12/src/net/net.go:614
net.(*TCPConn).readFrom(0xc000092050, 0x0, 0x0, 0xc0000386a8, 0x40b21a, 0x756f60)
        /usr/lib/go-1.12/src/net/tcpsock_posix.go:54 +0x13d
net.(*TCPConn).ReadFrom(0xc000092050, 0x0, 0x0, 0x7f4a00531008, 0xc000092050, 0x1)
        /usr/lib/go-1.12/src/net/tcpsock.go:103 +0x4e
io.copyBuffer(0x8256a0, 0xc000092050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.12/src/io/io.go:388 +0x2fc
io.Copy(...)
        /usr/lib/go-1.12/src/io/io.go:364
github.com/OperatorFoundation/shapeshifter-dispatcher/modes/transparent_tcp.copyLoop.func2(0xc0000180b0, 0x82e6c0, 0xc000092050, 0x0, 0x0, 0xc000060060)
        /home/(removed)/go/src/github.com/OperatorFoundation/shapeshifter-dispatcher/modes/transparent_tcp/transparent_tcp.go:328 +0xf9
created by github.com/OperatorFoundation/shapeshifter-dispatcher/modes/transparent_tcp.copyLoop
        /home/(removed)/go/src/github.com/OperatorFoundation/shapeshifter-dispatcher/modes/transparent_tcp/transparent_tcp.go:326 +0x124
```

**Comment by greengameplayer** [comment]
Tested out on Ubuntu Live 18.10 and same result.

**Comment by greengameplayer** [comment]
Gave up, moved to Shadowsocks.
